// ── Airport size classification ──────────────────────────────────────────────
//
// Where an airport's tier comes from — the sim's own runway length where it
// has been fetched, otherwise OurAirports' published class, otherwise
// 'unknown' — and the policy that turns a viewport's zoom and density into a
// tier to filter through. Nothing here talks to the network at runtime: the
// classification map is loaded once, from a file generated offline.

import fs from 'fs';
import path from 'path';
import type Database from 'better-sqlite3';
import type { AirportTier } from './queryTypes';

// ── the vocabulary ───────────────────────────────────────────────────────────

/** Tier codes as stored in the temp table and compared in SQL. Only 1, 2, 3
 *  and 5 are ever stored: 4 is the *absence* of a row, which is why the SQL
 *  reaches it with COALESCE(..., 4) rather than a NULL test. */
export const AIRPORT_TIER_CODE = {
  large: 1, medium: 2, small: 3, unknown: 4, other: 5,
} as const;

/** Inverse of AIRPORT_TIER_CODE, indexed by code; index 0 is unused. */
export const AIRPORT_TIER_BY_CODE = ['', 'large', 'medium', 'small', 'unknown', 'other'] as const;

/** The code an ident gets when nothing classifies it. Must equal
 *  AIRPORT_TIER_CODE.unknown — the SQL hard-codes this number. */
export const AIRPORT_TIER_UNKNOWN_CODE = 4;

/** The highest tier code. When the chosen tier is this, no filter is applied
 *  at all and the query is the unfiltered one. */
export const AIRPORT_TIER_LAST_CODE = 5;

/** The furthest the viewport budget may lift the tier. 'unknown' and 'other'
 *  are reached by zoom alone: an ident OurAirports does not carry is not
 *  claimed to be minor, and is not shown early just because the viewport
 *  holds few airports. */
export const AIRPORT_TIER_LAST_CLASSIFIED_CODE = 3;

/** Metres. The same two numbers the client uses to size the airport glyph:
 *  the symbol a viewer sees and the zoom it appears at must agree. Move one,
 *  move both. */
export const AIRPORT_TIER_LARGE_M = 2500;
export const AIRPORT_TIER_MEDIUM_M = 1200;

/** Lowest map zoom at which each tier is admitted. The airports kind itself
 *  is gated at NAVDATA_ZOOM_MIN.airports, so nothing here is reachable below
 *  that. 'unknown' shares the last step with 'other': an ident OurAirports
 *  does not carry, and whose detail has never been fetched, appears only when
 *  everything appears. */
export const AIRPORT_TIER_ZOOM_MIN = {
  large: 6, medium: 7, small: 8, unknown: 9, other: 9,
} as const;

/** Airports a single viewport response should aim to hold. At this count the
 *  expected nearest-neighbour spacing on a 1400x900 map is ~25 px, about 1.4
 *  times the widest airport glyph, so symbols stay individually readable. */
export const AIRPORT_VIEWPORT_BUDGET = 500;

const DEFAULT_TIERS_FILENAME = 'airport-tiers.json';

// The temp table this module installs. Created once per connection handle and
// dies with it; nothing is ever written to the replica file.
const AIRPORT_TIER_TABLE_DDL = `
  CREATE TEMP TABLE nav_airport_tier (
    ident TEXT PRIMARY KEY,
    tier  INTEGER NOT NULL
  ) WITHOUT ROWID`;

// ── the map ───────────────────────────────────────────────────────────────────

let tierMap = new Map<string, number>();
let mapVersion = 0;

/**
 * Reads the committed ident->tier file into the process-wide map. Never
 * downloads: the file is generated by hand and committed. A missing,
 * unreadable or self-inconsistent file logs one warning and leaves the map
 * empty, which disables thinning entirely rather than hiding every airport.
 */
export function loadAirportTiers(filePath?: string): void {
  const target = filePath ?? path.join(process.cwd(), DEFAULT_TIERS_FILENAME);
  const fail = (reason: string): void => {
    console.warn(`[AirportTiers] ${reason}; airport thinning is disabled`);
    setAirportTiers([]);
  };

  let raw: string;
  try {
    raw = fs.readFileSync(target, 'utf8');
  } catch (err) {
    fail(`could not read ${target}: ${(err as Error).message}`);
    return;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    fail(`${target} is not valid JSON: ${(err as Error).message}`);
    return;
  }

  const doc = parsed as { counts?: Record<string, unknown>; tiers?: Record<string, unknown> };
  if (!doc || typeof doc !== 'object' || typeof doc.tiers !== 'object' || doc.tiers === null) {
    fail(`${target} has no "tiers" object`);
    return;
  }

  const entries: [string, number][] = [];
  for (const codeStr of Object.keys(doc.tiers)) {
    const code = Number(codeStr);
    const idents = doc.tiers[codeStr];
    if (!Number.isInteger(code) || typeof idents !== 'string') {
      fail(`${target}: tier "${codeStr}" is not a valid entry`);
      return;
    }
    const split = idents.split(' ');
    const expected = doc.counts ? Number(doc.counts[codeStr]) : NaN;
    if (expected !== split.length) {
      fail(`${target}: tier ${codeStr} has ${split.length} idents but counts says ${doc.counts?.[codeStr]}`);
      return;
    }
    for (const ident of split) {
      if (ident !== '') entries.push([ident, code]);
    }
  }

  setAirportTiers(entries);
  console.log(`[AirportTiers] Loaded ${airportTierMapSize()} idents from ${target}`);
}

/** Test seam, mirroring setAirports() in the flight-log airport module.
 *  Bumps the map version so an already-installed temp table is rebuilt. */
export function setAirportTiers(entries: Iterable<readonly [string, number]>): void {
  const next = new Map<string, number>();
  for (const [ident, code] of entries) next.set(ident.toUpperCase(), code);
  tierMap = next;
  mapVersion++;
}

/** 0 when no classification data is loaded — the signal that thinning is
 *  off. */
export function airportTierMapSize(): number {
  return tierMap.size;
}

/** The OurAirports class of an ident: null when the map holds no row for it.
 *  null here means "OurAirports has no row", not "unclassified". */
export function ourAirportsTierOf(ident: string): AirportTier | null {
  const code = tierMap.get(ident.toUpperCase());
  return code === undefined ? null : (AIRPORT_TIER_BY_CODE[code] as AirportTier);
}

function tierFromMetres(m: number): AirportTier {
  if (m >= AIRPORT_TIER_LARGE_M) return 'large';
  if (m >= AIRPORT_TIER_MEDIUM_M) return 'medium';
  return 'small';
}

/**
 * The tier of one airport, from the two sources in order: the sim's own
 * longest runway where the detail has been fetched, then OurAirports, then
 * 'unknown'. Returns null only when neither source could be consulted — no
 * fetched runway and no classification data loaded — which is a different
 * statement from 'unknown' and must not be collapsed into it.
 *
 * longestRunwayM is the value already on the feature row: non-null only for a
 * detail-fetched airport with at least one runway whose length is known.
 */
export function airportTierOf(ident: string, longestRunwayM: number | null): AirportTier | null {
  if (longestRunwayM != null) return tierFromMetres(longestRunwayM);
  if (tierMap.size === 0) return null;
  return ourAirportsTierOf(ident) ?? 'unknown';
}

// ── the temp table ────────────────────────────────────────────────────────────

// Handle -> the map version last installed into it. A replica swap hands out
// a new Database object this map has never seen, so the swap needs no
// coordination with connection.ts: the next query simply installs afresh.
const installed = new WeakMap<Database.Database, number>();

/**
 * Makes sure this replica handle carries a snapshot of the current map in
 * temp.nav_airport_tier, creating it on first use and rebuilding it if the
 * map has been reseeded. A no-op when the map is empty.
 *
 * The table is per connection and dies with it, so a replica swap — which
 * hands out a new handle — is handled by the handle itself being unknown
 * here. Populating ~46k rows measures at ~46 ms and is paid once per handle.
 */
export function ensureAirportTierTable(db: Database.Database): void {
  if (tierMap.size === 0) return;
  const current = installed.get(db);
  if (current === mapVersion) return;

  if (current === undefined) {
    db.exec(AIRPORT_TIER_TABLE_DDL);
  } else {
    db.exec('DELETE FROM temp.nav_airport_tier');
  }
  const insert = db.prepare('INSERT INTO temp.nav_airport_tier (ident, tier) VALUES (?, ?)');
  const insertAll = db.transaction((rows: [string, number][]) => {
    for (const [ident, tier] of rows) insert.run(ident, tier);
  });
  insertAll([...tierMap.entries()]);
  installed.set(db, mapVersion);
}

// ── tier choice by zoom and viewport count ────────────────────────────────────

/** The highest tier code the zoom alone admits: the lowest tier
 *  chooseAirportTier() can return. Derived from AIRPORT_TIER_ZOOM_MIN, never
 *  hard-coded, so that table is the only place the zoom thresholds can be
 *  changed. */
export function airportTierFloor(zoom: number): number {
  let floor = 0;
  for (const tier of Object.keys(AIRPORT_TIER_ZOOM_MIN) as (keyof typeof AIRPORT_TIER_ZOOM_MIN)[]) {
    if (AIRPORT_TIER_ZOOM_MIN[tier] <= zoom) floor = Math.max(floor, AIRPORT_TIER_CODE[tier]);
  }
  return floor;
}

/**
 * The tier to filter through, given the unfiltered per-tier counts of a
 * viewport and its zoom. Zoom sets a floor; a viewport that still fits the
 * budget lifts it, but never past the last classified tier and never below
 * the floor. Pure: no database, no clock, no I/O.
 *
 * byTierCounts is keyed by tier code; a missing key counts as zero.
 */
export function chooseAirportTier(byTierCounts: Readonly<Record<number, number>>, zoom: number): number {
  const floor = airportTierFloor(zoom);
  let chosen = floor;
  let cum = 0;
  for (let t = 1; t <= AIRPORT_TIER_LAST_CLASSIFIED_CODE; t++) {
    cum += byTierCounts[t] ?? 0;
    if (cum <= AIRPORT_VIEWPORT_BUDGET && t > chosen) chosen = t;
  }
  return chosen;
}
